services:
  pg:
    image: postgres:16-alpine
    ports:
      - "7000:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: neochat
    volumes:
      - pgdata:/var/lib/postgresql/pgdata
    
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    command:
      [
        "--proactor_threads=2",
        "--maxmemory=600mb",
        "--lock_on_hashtags"
      ]

volumes:
  pgdata:
  dragonflydata:
